version: '3.3'
services:
        build:
                image: openjdk:11
                user: "${DOCKER_COMPOSE_RUN_AS_USER}"
                working_dir: /app
                volumes:
                        - .:/app
                        - gradle-dist:/root/.gradle
                command: ./gradlew clean build
                environment:
                        - APP_AUTH_JWT_SECRET

        app:
                image: openjdk:11
                user: "${DOCKER_COMPOSE_RUN_AS_USER}"
                working_dir: /app
                volumes:
                        - .:/app
                        - gradle-dist:/root/.gradle
                ports:
                        - '8080:8080'
                        - '5005:5005'
                command: ./gradlew bootRun
                environment:
                        - APP_AUTH_JWT_SECRET

volumes:
        gradle-dist:
                external: false
